import type { Metadata } from "next";
// import { Segoe Ui } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/Provider";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={manrope.className}>{children}</body>
      </Providers>
    </html>
  );
}
